sudo: required
language: node_js
node_js:
  - "6"
cache: yarn
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libcairo2-dev libjpeg8-dev libpango1.0-dev libgif-dev build-essential g++